name: Deploy to WordPress.org
env:  
  PUBLISH_PATH: '${{ github.workspace }}/publish'
  PLUGIN_NAME: riotd-reddit-image-of-the-day
on:
  workflow_dispatch:
    inputs:
      runtpye:
        description: 'Full or Artifact'
        required: false
        default: 'Full'
  release:
    types: [published]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:   
    - name: Checkout code
      uses: actions/checkout@v2    
    - name: 'Get last release tag'      
      id: releasetag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
          fallback: 1.0.0   
    - name: Create artifact      
      run:                
        zip -X -r '${{ github.workspace }}/${{env.PLUGIN_NAME}}-${{ steps.releasetag.outputs.tag }}.zip' . -x *.git* node_modules/\* .* "*/\.*" ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md *.dist composer.* dev-helpers** build**
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
          args: '${{ github.workspace }}/${{env.PLUGIN_NAME}}-${{ steps.releasetag.outputs.tag }}.zip'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}                  
    - name: WordPress Plugin Deploy
      if: github.event.inputs.runtype == 'Full'
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: riotd-reddit-image-of-the-day                